### ISSUE TITLE
phalcon compilation failed

### ISSUE THREAD

**Issue by lifei6671** [MilesChou/docker-phalcon#1]
This has been stopped：
`
gcc -I. -I/var/www/html/cphalcon-3.0.0/build/php7/64bits -DPHP_ATOM_INC -I/var/www/html/cphalcon-3.0.0/build/php7/64bits/include -I/var/www/html/cphalcon-3.0.0/build/php7/64bits/main -I/var/www/html/cphalcon-3.0.0/build/php7/64bits -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DPHALCON_RELEASE -DHAVE_CONFIG_H -march=native -mtune=native -O2 -fomit-frame-pointer -fvisibility=hidden -c /var/www/html/cphalcon-3.0.0/build/php7/64bits/phalcon.zep.c  -fPIC -DPIC -o .libs/phalcon.o
`
I do not know how to do it？

**Comment by MilesChou** [comment]
Which `Dockerfile` do you build? I build from [7.0/Dockerfile](7.0/Dockerfile) and [7.0/alpine/Dockerfile](7.0/alpine/Dockerfile) is OK

You can try increase memory if you use VM. I remember that required 2GB+ when compile Phalcon 2.x . Maybe this issue is the same.

**Comment by lifei6671** [comment]
Thanks。
I waited twenty minutes to finish.

**Comment by MilesChou** [comment]
That's too long... . May I have your info of machine about CPU / RAM / Docker Version / etc.?

**Comment by MilesChou** [comment]
BTW, I built it used Macbook Pro, Intel Core i7, 16GB, and waited about 3 minutes.

**Comment by lifei6671** [comment]
I used VM，Ubuntu16.04,Intel Core I5 1G.

**Comment by MilesChou** [comment]
Okay! It maybe lack of resource. I will noted in README.md file.

**Comment by fizzka** [comment]
info:

seems to been fixed:
https://github.com/phalcon/cphalcon/issues/13143
