### ISSUE TITLE
strange build behavior

### ISSUE THREAD

**Issue by fizzka** [MilesChou/docker-phalcon#13]
if I pull image from autobuilded docker hub - php periodically coredumped (on different virtual machines).
if I build image manually - thats ok.

tested image: 7.1/alpine

**Comment by MilesChou** [comment]
But it seem the same problem when use official php image 😂

**Comment by fizzka** [comment]
i'm not sure. fails occur on phalcon projects in phalcon code only =)

the only thing i checked, that if  I manually rebuild same image on same
vitrual host - problem is goes away

2017-10-10 7:25 GMT+03:00 MilesChou <notifications@github.com>:

**Comment by fizzka** [comment]
upd:
traps: php[7940] trap invalid opcode ip:7ff533cf03db sp:7fff12c89e40 error:0 in phalcon.so[7ff5338ff000+685000]

it seems bug in virtualization flags:
https://github.com/phalcon/cphalcon/issues/1739#issuecomment-31346953

**Comment by MilesChou** [comment]
I think that we should do some integration test after build image on travis. Maybe run a Phalcon CLI application.

**Comment by fizzka** [comment]
phalcon/cphalcon/issues/#13143

**Comment by fizzka** [comment]
phalcon/cphalcon#13143

I think there is a problem in gcc optimization flags in phalcon build (different build platform in travis-ci (i suppose amd cpu, or very modern instructions set) and docker-pull platforms cpu

**Comment by fizzka** [comment]
fixed by changing build options

**Comment by fizzka** [comment]
info:

seems to been fixed: phalcon/cphalcon#13143
