### ISSUE TITLE
docker hub readme isn't autoupdating

### ISSUE THREAD

**Issue by fizzka** [MilesChou/docker-phalcon#18]
https://hub.docker.com/r/mileschou/phalcon/ - no actual info about php7.2 and latest phalcon version (3.2.4)

**Comment by MilesChou** [comment]
Let’s me update today

**Comment by MilesChou** [comment]
Finished! 

BTW, I didn't use auto build because there has a little bit difference between GitHub markdown and DockerHub markdown. :joy:

**Comment by fizzka** [comment]
great!
