### ISSUE TITLE
Build phalcon 4.0.0-alpha

### ISSUE THREAD

**Issue by hosseinsalemi** [MilesChou/docker-phalcon#37]
Please build phalcon 4.x and phalcon devtools 4.x

**Comment by djumpen** [comment]
@hosseinsalemi Have you successfully built such image? I can't configure phalcon4 with psr extension.

**Comment by wajdijurry** [comment]
+1 but for stable release

**Comment by MilesChou** [comment]
I will build Phalcon 4.x when stable release.

**Comment by ruudboon** [comment]
If you need some help with this ping me on Discord. V4 isn't far away ;)

**Comment by alpody** [comment]
> 
> 
> I will build Phalcon 4.x when stable release.

Phalcon 4 have done.  https://blog.phalcon.io/post/phalcon-4-0-0-released

**Comment by MilesChou** [comment]
Phalcon 4 is no longer support PHP 5.x ~ 7.1, so that I will adjust the readme structure.

**Comment by MilesChou** [comment]
Need Composer before install devtools.

```
$ docker run -it --rm mileschou/phalcon sh -c 'docker-phalcon-install-devtools; phalcon'                         
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132    0   132    0     0    191      0 --:--:-- --:--:-- --:--:--   191
100 3266k    0 3266k    0     0   694k      0 --:--:--  0:00:04 --:--:-- 1072k
ERROR: Please run composer install
```

@Jeckerson Can you [build an image](https://github.com/MilesChou/docker-phalcon/pull/41#issuecomment-562971452) for this image to require devtools phar?

**Comment by Jeckerson** [comment]
@MilesChou Could you build and push inside your org on docker hub?

**Comment by Jeckerson** [comment]
Also, for v4 devtools we already generate phalcon.phar

![image](https://user-images.githubusercontent.com/3289702/71443736-a3d1a780-2704-11ea-89a2-2e5aff377e74.png)

**Comment by MilesChou** [comment]
@Jeckerson Great! I can download phar from GitHub release. thx.

**Comment by MilesChou** [comment]
Update to 4.0.0, both Phalcon framework and devtools.
