### ISSUE TITLE
COPY failed: no source files were specified

### ISSUE THREAD

**Issue by yongliu1992** [MilesChou/docker-phalcon#38]
hi, I have a problem  building
Step 7/7 : COPY docker-phalcon-* /usr/local/bin/
COPY failed: no source files were specified
I don't know how go find  the `docker-phalcon-*` file, if i don't complete this step, will it affect the use ?

**Comment by MilesChou** [comment]
You can see [Makefile](https://github.com/MilesChou/docker-phalcon/blob/master/Makefile). It an example to know how to build.

In Makefile, the Docker build context is project root, and the `docker-phalcon-*` file location at project root, too.

**Comment by yongliu1992** [comment]
thank you~

**Comment by AnatolyAstapov** [comment]
@yongliu1992 
Answer here please , what did you do for the result?
I can't do it.
Step 7/7 : COPY docker-phalcon-* /usr/local/bin/
ERROR: Service 'php' failed to build: COPY failed: no source files were specified

**Comment by yongliu1992** [comment]
You can see Makefile. It an example to know how to build.
In Makefile, the Docker build context is project root, and the docker-phalcon-* file location at project root, too.
It is not affect the use

**Comment by yongliu1992** [comment]
> @yongliu1992
> Answer here please , what did you do for the result?
> I can't do it.
> Step 7/7 : COPY docker-phalcon-* /usr/local/bin/
> ERROR: Service 'php' failed to build: COPY failed: no source files were specified

You can see Makefile. It an example to know how to build.
In Makefile, the Docker build context is project root, and the docker-phalcon-* file location at project root, too.
It is not affect the use
