### ISSUE TITLE
Phalcon updates

### ISSUE THREAD

**Issue by andejong** [MilesChou/docker-phalcon#43]
Hello, can you please update phalcon devtools to 4.0.1 and Phalcon to 4.0.2?

**Comment by MilesChou** [comment]
I bump Phalcon to version 4.0.2, but Devtools has error at 4.0.1.

You can exec the follow command to install specify version

```
docker run -it --rm mileschou/phalcon docker-phalcon-install-devtools 4.0.1
```

**Comment by fizzka** [comment]
#48
