### ISSUE TITLE
Add PHP 8.0 support

### ISSUE THREAD

**Issue by MilesChou** [MilesChou/docker-phalcon#47]
See https://www.php.net/releases/8.0/en.php

**Comment by Jeckerson** [comment]
You can already do that. Here is example that we are using for local development:
https://github.com/phalcon/cphalcon/blob/master/docker/8.0/Dockerfile

**Comment by MilesChou** [comment]
Official issue link
https://github.com/phalcon/cphalcon/issues/15186

**Comment by Jeckerson** [comment]
@MilesChou Could you make new `Dockerfile`'s shipped with Phalcon v5.alpha?

**Comment by MilesChou** [comment]
I try on alpha3

https://github.com/phalcon/cphalcon/tree/v5.0.0alpha3

**Comment by MilesChou** [comment]
@Jeckerson Compile work but `phalcon.so` file load failed.

I don't know why because I just a PHP developer.

https://github.com/MilesChou/docker-phalcon/runs/3132198314?check_suite_focus=true#step:3:45868

**Comment by Jeckerson** [comment]
Try to use `safe` folder instead of `64bits`.

**Comment by MilesChou** [comment]
> Try to use `safe` folder instead of `64bits`.

Use safe folder but same problem again.

https://github.com/MilesChou/docker-phalcon/runs/3157993047?check_suite_focus=true#step:3:45939

**Comment by MilesChou** [comment]
@Jeckerson Solved. Because load Phalcon extension first by default. Adjust the PSR to first and work on Debian and Alpine. 

See commit https://github.com/MilesChou/docker-phalcon/pull/50/commits/053496fdc5994aa13bced30c98f39d1b71c0e27f

**Comment by Jeckerson** [comment]
@MilesChou Could you bump version to `RC1` please? And also add PHP8.1.

**Comment by MilesChou** [comment]
I tried but build failed...

https://github.com/MilesChou/docker-phalcon/runs/6844355654?check_suite_focus=true

**Comment by Jeckerson** [comment]
> I tried but build failed...
> 
> https://github.com/MilesChou/docker-phalcon/runs/6844355654?check_suite_focus=true

Seems to work. Btw PSR extension is not required any more since `RC1` version.

**Comment by MilesChou** [comment]
OK, I update code on 8.0 and 8.1 Dockerfile
https://github.com/MilesChou/docker-phalcon/actions/runs/2485532716

**Comment by Jeckerson** [comment]
@MilesChou it seems that it can be closed.

**Comment by MilesChou** [comment]
Done, Thx @Jeckerson
