### ISSUE TITLE
alpine image not functional

### ISSUE THREAD

**Issue by fizzka** [MilesChou/docker-phalcon#6]
docker run -i -t --rm mileschou/phalcon:alpine php -m

output:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/phalcon.so' - Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20160303/phalcon.so: No such file or directory in Unknown on line 0
[PHP Modules]
Core
ctype
curl
[...]

**Comment by MilesChou** [comment]
Okay, I see the error message in Travis CI log when do compilation.

I will try to resolve this error.

**Comment by fizzka** [comment]
i suppose you need *pcre-dev* package in build-deps =)

**Comment by fizzka** [comment]
good =)

**Comment by MilesChou** [comment]
I did. Thx for your suggestion =)
