### ISSUE TITLE
phalcon 3.2 released

### ISSUE THREAD

**Issue by fizzka** [MilesChou/docker-phalcon#7]
https://github.com/phalcon/cphalcon/releases/tag/v3.2.0

need to update and think about versioning ;)

**Comment by MilesChou** [comment]
Thx for your feedback! I will upgrade in this day.

**Comment by fizzka** [comment]
nice to see this)

do you have any clear look on build matrix (php versions) x (phalcon versions)?

maybe, some Dockerfile-generation tool?

**Comment by MilesChou** [comment]
No, I didn't think about this idea. Because I think that will become more complex in README description.
