### ISSUE TITLE
improve module enabling

### ISSUE THREAD

**Issue by fizzka** [MilesChou/docker-phalcon#9]
what about to replace low-level
`echo "extension=phalcon.so" > /usr/local/etc/php/conf.d/phalcon.ini`
with bundled
`docker-php-ext-enable phalcon`
?

**Comment by MilesChou** [comment]
Actually, I didn't know that this script (`docker-php-ext-enable`) can be used at that time :sweat_smile:

I will improve for this issue. Thank you for feedback =)

**Comment by fizzka** [comment]
https://hub.docker.com/_/php/

How to install more PHP extensions
We provide the helper scripts docker-php-ext-configure, docker-php-ext-install, and docker-php-ext-enable to more easily install PHP extensions.

good luck)
